#!/bin/bash

# Test Guide for Recharge & Bill Payment Features

echo "======================================"
echo "Recharge & Bill Payment Feature Test"
echo "======================================"
echo ""

# Check if backend is running
echo "1. Checking if backend is running..."
if lsof -i:5000 > /dev/null 2>&1; then
    echo "✅ Backend is running on port 5000"
else
    echo "❌ Backend is not running"
    echo "   Start with: cd backend && npm run dev"
    exit 1
fi

# Check if frontend is running
echo ""
echo "2. Checking if frontend is running..."
if lsof -i:5173 > /dev/null 2>&1; then
    echo "✅ Frontend is running on port 5173"
else
    echo "❌ Frontend is not running"
    echo "   Start with: npm run dev"
    exit 1
fi

echo ""
echo "======================================"
echo "Test Scenarios"
echo "======================================"
echo ""
echo "📱 MOBILE RECHARGE TEST:"
echo "1. Navigate to: http://localhost:5173/recharge"
echo "2. Enter mobile: 9876543210 (Jio)"
echo "3. Select a plan from any category"
echo "4. Click 'Recharge'"
echo "5. Check toast notification"
echo ""
echo "📺 DTH RECHARGE TEST:"
echo "1. Click 'DTH Recharge' tab"
echo "2. Select 'Tata Sky' operator"
echo "3. Enter Customer ID: 1234567890"
echo "4. Select a plan"
echo "5. Click 'Recharge'"
echo ""
echo "💡 ELECTRICITY BILL TEST:"
echo "1. Navigate to: http://localhost:5173/bills"
echo "2. Select 'Adani Electricity Mumbai'"
echo "3. Enter Account: ACC12345"
echo "4. Click 'Fetch Bill'"
echo "5. Review bill and click 'Pay'"
echo ""
echo "💧 WATER BILL TEST:"
echo "1. Click 'Water' tab"
echo "2. Select provider"
echo "3. Enter account number"
echo "4. Fetch and pay bill"
echo ""
echo "🔥 GAS BILL TEST:"
echo "1. Click 'Gas' tab"
echo "2. Select provider"
echo "3. Enter account number"
echo "4. Fetch and pay bill"
echo ""
echo "======================================"
echo "Sample Test Data"
echo "======================================"
echo ""
echo "Mobile Numbers:"
echo "  9876543210 - Jio"
echo "  9123456789 - Airtel"
echo "  9988776655 - Vi"
echo "  9000000000 - BSNL"
echo ""
echo "DTH Customer IDs:"
echo "  Any 10-digit number works"
echo ""
echo "Bill Account Numbers:"
echo "  Any alphanumeric works (mock data)"
echo ""
echo "======================================"
echo "API Endpoints to Test"
echo "======================================"
echo ""
echo "Recharge API:"
echo "  POST http://localhost:5000/api/v1/recharge/detect-operator"
echo "  GET  http://localhost:5000/api/v1/recharge/plans?operator=JIO"
echo "  POST http://localhost:5000/api/v1/recharge/mobile"
echo ""
echo "Bills API:"
echo "  GET  http://localhost:5000/api/v1/bills/operators/ELECTRICITY"
echo "  POST http://localhost:5000/api/v1/bills/fetch"
echo "  POST http://localhost:5000/api/v1/bills/pay"
echo ""
echo "======================================"
echo "✅ Ready to test!"
echo "======================================"
